version: '3.1'

services:
  postgres:
    image: postgres:12.1
    deploy:
      replicas: 1
    secrets:
      - psql-pwd
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pwd
    volumes:
      - drupal-data:/var/lib/postgresql/data

  drupal:
    image: drupal:8.2
    ports:
      - 9090:80
    deploy:
      replicas: 1
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data:

secrets:
  psql-pwd:
    external: true


